# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        acl:
            anonymous: ~
            http_basic: ~

        pattern:
            # Première méthode (exemple pattern)
            pattern: /newmenu
            anonymous: false
            http_basic: ~

    access_control:
        - { path: /newmenu, roles: IS_AUTHENTICATED_ANONYMOUSLY }
